app/urls.py
from os import name
from django.urls import path
from . import views

app_name='app'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('add/', views.AddView.as_view(), name='add'),
    path('post/', views.PostView.as_view(), name='post'),
    path('<slug:slug>/', views.SingleView.as_view(), name='single'),
    path('edit/<int:pk>/', views.EditView.as_view(), name='edit'),
    path('delete/<int:pk>/', views.Delete.as_view(), name='delete'),
]

core/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls', namespace='app')),  
]

app/models.py
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.contrib.auth.models import User
from django.utils.translation import gettext as _

class Core(models.Model):
    title = models.CharField(_("title"), max_length=200)
    excerpt = models.TextField(_("excerpt"), null=True)
    author = models.ForeignKey(User, verbose_name=_("Author"),related_name='core', on_delete=models.CASCADE)
    slug = models.SlugField(_("slug"), unique=True)
    updated = models.DateTimeField(_("updated"), auto_now=True)
    published = models.DateTimeField(_("published"), auto_now_add=False)

    def get_absolute_url(self):
        return reverse("app:single", args={ self.slug})
    
    class Meta:
        ordering = ['-published']
    
    def __str__(self):
        return self.title
    

app/forms.py
from django import forms
from django.db.models import fields
from .models import Core

class PostForm(forms.ModelForm):
    class Meta:
        model = Core
        fields = '__all__'

app/views.py
from django.urls.base import reverse_lazy
from .models import Core
from django.shortcuts import render
from django.views.generic import ListView, DetailView , UpdateView, DeleteView,CreateView



class IndexView(ListView):
    model = Core
    template_name = 'core/index.html'
    context_object_name = 'index'

class SingleView(DetailView):
    model = Core
    template_name = 'core/single.html'
    context_object_name = 'post'

class PostView(ListView):
    model = Core
    template_name = 'core/posts.html'
    context_object_name = 'post_list'

class AddView(CreateView):
    model = Core
    # fields = ['name']
    template_name = 'core/add.html'
    fields = '__all__'
    success_url = reverse_lazy('app:post')

class EditView(UpdateView):
    model = Core
    # fields = ['name']
    template_name = 'core/edit.html'
    fields = '__all__'
    pk_url_kwarg = 'pk'
    success_url = reverse_lazy('app:post')

class Delete(DeleteView):
    model = Core
    # fields = ['name']
    template_name = 'core/confirm_delete.html'

    pk_url_kwarg = 'pk'
    success_url = reverse_lazy('app:post')

templates/core/add.html
{% extends 'core/base.html' %}

{% load widget_tweaks %}

{% block content %}

    <div class="container pt-5">
        <form action="" method="post" novalidate> 
            {% csrf_token %}

            {% for field in form.visible_fields %}
                <div class="form-group">
                    <label for="{{field.id_for_label}}">{{field.label}}</label>
                    {{field|add_class:'form-control'}}
                    {% for error in field.errors %}
                        <span class="help-block">{{error}}</span>
                    {% endfor %}
                </div>
            {% endfor %}
            <div class="form-group">
                <button class="btn btn-success" type="submit"><span class="glyphicon glyphicon-ok"></span>SAve</button>
                <a href="{% url 'app:post' %}" class="btn btn-default">Cancel</a>
            </div>
        </form>
    </div>
{% endblock content %}

templates/core/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <title>Hello, world!</title>
  </head>
  <body>

    {% include 'core/nav.html' %}
    
    {% block content %}{% endblock content %}

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

templates/core/confirm_delete.html
{% extends 'core/base.html' %}

{% block content %}
    <div class="container pt-5">
        <form action="" method="post">
        {% csrf_token %}
        <p>Are you sure want to delete "{{object}}"</p>
        <input type="submit" value="Confirm">
    </form>
    </div>
{% endblock content %}

templates/core/edit.html
{% extends 'core/base.html' %}

{% load widget_tweaks %}

{% block content %}

    <div class="container pt-5">
        <form action="" method="post" novalidate> 
            {% csrf_token %}

            {% for field in form.visible_fields %}
                <div class="form-group">
                    <label for="{{field.id_for_label}}">{{field.label}}</label>
                    {{field|add_class:'form-control'}}
                    {% for error in field.errors %}
                        <span class="help-block">{{error}}</span>
                    {% endfor %}
                </div>
            {% endfor %}
            <div class="form-group">
                <button class="btn btn-success" type="submit"><span class="glyphicon glyphicon-ok"></span>Edit</button>
                <a href="{% url 'app:post' %}" class="btn btn-default">Cancel</a>
            </div>
        </form>
    </div>
{% endblock content %}

templates/core/index.html
{% extends 'core/base.html' %}

{% block content %}
    <div class="album py-5 bg-light">
        <div class="container">
            <div class="row">
                {% for core in index %}
                    <div class="col-md-4">
                        <div class="card mb-4 box-shadow">
                            <img src="" alt="card" class="card-img-top">
                            <div class="card-body">
                                <h4 class=""><a href="{{core.get_absolute_url}}">{{core.title}}</a></h4>
                                <p class="card-text"></p>
                                <div class="d-flex justify-content-between align-items-center">
                                    <div class="">
                                        <small class="text-muted">9 mins</small>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock content %}

templates/core/nav.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'app:index' %}">Home </a>
      </li>
      <li class="nav-item active">
        <a href="{% url 'app:post' %}" class="nav-link">Manage Post</a>
      </li>
    </ul>
  </div>
</nav>

templates/core/posts.html
{% extends 'core/base.html' %}  

{% block content %}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
<div class="navbar-brand">Post Admin</div>
<div class="collapse navbar-collapse" id="navbarNav">
    <div class="navbar-nav">
        <li class="nav-itme active">
            <a href="{% url 'app:add' %}" class="nav-link">Add New</a>
        </li>
    </div>
</div>
</nav>

<div class="album py-5 bg-light">
    <div class="container">
        <div class="row">
            {% for post in post_list %}
                <div class="col-md-4">
                    <div class="card md-4 box-shadow">
                        <img src="https://via:placehodler.com/150x100" alt="" class="card-img-top">
                        <div class="card-body">
                            <h4 class="lead"><a href="{% url 'app:single' post.pk%}" class="text-dark">{{post.title}}</a></h4>
                            <p class="card-text"></p>
                            <div class="d-flex justify-content-between align-items-center">
                                <div class="btn-group">
                                    <a href="{{post.get_absolute_url}}" role="button" class="btn btn-sm btn-outline-primary">View</a>
                                    <a href="{% url 'app:edit' post.pk %}" role="button" class="btn btn-sm btn-outline-primary">Edit</a>
                                    <a href="{% url 'app:delete' post.pk %}" role="button" class="btn btn-sm btn-outline-primary">Delete</a>
                                </div>
                                <small class="text-muted">9 mins</small>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock content %}

templates/core/single.html
{% extends 'core/base.html' %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-12 pt-5">
                <img src="" alt="img" class="card-img-top">
                <h2 class="pt-5">{{post.title}}</h2>
                <p>{{post.excerpt}}</p>
            </div>
        </div>
    </div>
{% endblock content %} 